version: '3.7'

networks:
  backend:
#    external:
#      name: global-backend

volumes:
  db:

services:
  web:
    image: pmphillip/pm-shopware-php-nginx:php-7.2
    container_name: "${PROJECT_NAME}-shop"
    hostname: "${PROJECT_NAME}"
    expose:
      - 80
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html:delegated             # Remove or comment for mutagen
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_LOCAL}
      MYSQL_USER: ${MYSQL_USER_LOCAL}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_LOCAL}
      MYSQL_HOST: mysql
      ES_HOST: ${ES_HOST}
      SHOPWARE_ENV: ${SHOPWARE_ENV}
      VIRTUAL_HOST: ${SHOP_URL_LOCAL}
    networks:
      - backend

  mysql:
    image: mysql:5.7.20
    container_name: "${PROJECT_NAME}-mysql"
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
      - ./configs/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=v399efJP
      - MYSQL_DATABASE=${MYSQL_DATABASE_LOCAL}
      - MYSQL_USER=${MYSQL_USER_LOCAL}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD_LOCAL}
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}-phpmyadmin"
    environment:
      PMA_HOSTS: mysql
      PMA_USER: root
      PMA_PASSWORD: v399efJP
      TZ: "Europe/Berlin"
      VIRTUAL_HOST: phpmyadmin.${SHOP_URL_LOCAL}
    expose:
      - 80
    ports:
      - "8083:80"
    networks:
      - backend
